garf-make: feat: `--skip`

diff --git a/garf/make b/garf/make
--- a/garf/make
+++ b/garf/make
@@ -4,29 +4,98 @@ src="$(     ~/scripts/cmd/garf +dir 'src')"      || { code="$?"; echo "$src";   
 unedited="$(~/scripts/cmd/garf +dir 'unedited')" || { code="$?"; echo "$unedited"; exit "$code"; }
 posts="$(   ~/scripts/cmd/garf +dir 'posts')"    || { code="$?"; echo "$posts";    exit "$code"; }
 
-date="$1"
-if [ ! "$date" ]; then
+date=''
+twothirds='' # --twothirds-adjust for comic-format
+name=''      # Custom directory name
+skip=0       # Skip existing post check
+
+while true; do
+    arg="$1"
+    [ -n "$arg" ] || break
+    shift
+
+    case "$arg" in
+        -r|--recent)
+            if [ -n "$date" ]; then
+                echo 'garf make: cannot specify date twice'
+                exit 1
+            fi
+            date="$(~/scripts/cmd/garf +recent || exit 1)"
+            if [ -z "$date" ]; then
+                echo 'garf make: no recent comic'
+                exit 1
+            fi
+            ;;
+
+        -t|--twothirds)
+            value="$1"
+            if [ -z "$value" ]; then
+                echo "garf make: missing value for $arg"
+                exit 1
+            fi
+            shift
+            if [ -n "$twothirds" ]; then
+                echo 'garf make: cannot specify twothirds twice'
+                exit 1
+            fi
+            twothirds="$value"
+            ;;
+
+        -n|--name)
+            value="$1"
+            if [ -z "$value" ]; then
+                echo "garf make: missing value for $arg"
+                exit 1
+            fi
+            shift
+            if [ -n "$name" ]; then
+                echo 'garf make: cannot specify name twice'
+                exit 1
+            fi
+            name="$value"
+            ;;
+
+        -s|--skip)
+            if [ "$skip" = 1 ]; then
+                echo 'garf make: cannot specify skip twice'
+                exit 1
+            fi
+            skip=1
+            ;;
+
+        -*)
+            echo "garf make: invalid option $arg"
+            exit 1
+            ;;
+
+
+        *)
+            if [ -n "$date" ]; then
+                echo 'garf make: cannot specify date twice'
+                exit 1
+            fi
+            date="$arg"
+            ;;
+    esac
+done
+
+if [ -z "$date" ]; then
     echo 'garf make: date not given'
     exit 1
 fi
-shift
 
-# Optional
-twothirds="$1"
-if [ -n "$twothirds" ]; then
-    shift
-else
+if [ -z "$twothirds" ]; then
     twothirds='0'
 fi
 
-name="$1"
-# Use recently shown comic, instead of date
-if [ "$date" = '-r' ]||[ "$date" = '--recent' ]; then
-    date="$(~/scripts/cmd/garf +recent || exit 1)"
-    if [ ! "$date" ]; then
-        echo 'garf make: no recent comic'
-        exit 1
+# Create unique name for folder, if not specified as argument
+if [ -z "$name" ]; then
+    if date -d "$date" +'%A' | grep -q 'Sunday';
+        then case='upper'
+        else case='lower'
     fi
+    id=$(tr -dc "[:$case:]" < /dev/urandom | head -c 4)
+    name="$id:$date"
 fi
 
 # Use filename if date is image path
@@ -51,25 +120,17 @@ for file in "$unedited/"*'/date'; do
         exit 1
     fi
 done
-for file in "$posts/"*'/date'; do
-    if [ "$(cat "$file")" = "$date" ]; then
-        echo 'garf make: comic has already been translated with that date'
-        exit 1
-    fi
-done
+if [ "$skip" = 0 ]; then
+    for file in "$posts/"*'/date'; do
+        if [ "$(cat "$file")" = "$date" ]; then
+            echo 'garf make: comic has already been translated with that date'
+            exit 1
+        fi
+    done
+fi
 
 # Convert image to square format, with watermark
 ~/scripts/cmd/garf +format "$input" "$unedited/$date.png" "$twothirds" || exit 1
-
-# Create unique name for folder, if not specified as argument
-if [ ! "$name" ]; then
-    if date -d "$date" +'%A' | grep -q 'Sunday';
-        then case='upper'
-        else case='lower'
-    fi
-    id=$(tr -dc "[:$case:]" < /dev/urandom | head -c 4)
-    name="$id:$date"
-fi
 
 # Create other files from image
 ~/scripts/cmd/garf +organize "$unedited/$date.png" "$unedited/$name" || exit 1
